INSERT INTO DOMAIN (NAME) VALUES ('google.com');
INSERT INTO DOMAIN (NAME) VALUES ('yahoo.com');
INSERT INTO DOMAIN (NAME) VALUES ('evil.com');
INSERT INTO DOMAIN (NAME) VALUES ('me.com');
INSERT INTO DOMAIN (NAME) VALUES ('sdfsd.com');
